# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04dfd79e0e0711211341f8d830e8b79874e1791fb28e82fdeb9735e965fd03b5913d6fd768efc56d6d399058acf88854fe2de81368b194a58f170b0ff3ec1a2e

test:
  secret_key_base: f7902da306d94a2bb3db4ef20592d73118b7883032fae2007eae82d1da4086e917d0c6139708464ed781b6cf0a785bf84f01955efacaf9387af226af41fd44bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
